[
    {
        "_id": "1",
        "user": "1",
        "name": "M Husnain Raza",
        "description": "M Husnain Raza M Husnain Raza M Husnain Raza M Husnain RazaM Husnain Raza M Husnain RazaM Husnain Raza M Husnain Raza",
        "website": "http://codeacademia.com",
        "phone": "03037900571",
        "email": "razarai663@gmail.com",
        "address": "razarai663 lahore",
        "careers": ["web", "UI/UX", "Business"],
        "housing": true,
        "jobAssistance": true,
        "jobGuarantee": false,
        "acceptGi": true,
    },
    {
        "_id": "2",
        "user": "2",
        "name": "M Husnain Raza",
        "description": "M Husnain Raza M Husnain Raza M Husnain Raza M Husnain RazaM Husnain Raza M Husnain RazaM Husnain Raza M Husnain Raza",
        "website": "http://codeacademia.com",
        "phone": "03037900571",
        "email": "razarai663@gmail.com",
        "address": "razarai663 lahore",
        "careers": ["web", "UI/UX", "Business"],
        "housing": true,
        "jobAssistance": true,
        "jobGuarantee": false,
        "acceptGi": true,
    },
    {
        "_id": "3",
        "user": "3",
        "name": "M Husnain Raza",
        "description": "M Husnain Raza M Husnain Raza M Husnain Raza M Husnain RazaM Husnain Raza M Husnain RazaM Husnain Raza M Husnain Raza",
        "website": "http://codeacademia.com",
        "phone": "03037900571",
        "email": "razarai663@gmail.com",
        "address": "razarai663 lahore",
        "careers": ["web", "UI/UX", "Business"],
        "housing": true,
        "jobAssistance": true,
        "jobGuarantee": false,
        "acceptGi": true,
    },

]